name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests for all workspace members
        run: cargo test --workspace --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy for all workspace members
        run: cargo clippy --workspace -- -D warnings

  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build all workspace members
        run: cargo build --workspace --verbose

      - name: Build canon-protocol library
        run: cargo build -p canon-protocol --verbose

      - name: Build canon-cli binary
        run: cargo build -p canon-cli --verbose

      - name: Check that binary runs
        run: cargo run -p canon-cli -- --version